#!/bin/bash

echo " The start of something big"

source /.env

export DEMO_ROOT="/demo_scripts/ejfat_demos/"
export EJFAT_IP_VERSION=4

export LBADM=lbadm
export E2SAR_PERF=e2sar_perf

export EJFAT_URI=$EJFAT_URI_BETA

echo " EJFAT URI IS "
echo $EJFAT_URI_BETA
echo $EJFAT_URI
echo " End URI summary"

