#!/bin/bash
#SBATCH -N 2
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J ejfat_file_test
#SBATCH --mail-user=yak@es.net
#SBATCH --mail-type=ALL
#SBATCH -t 00:02:00

#OpenMP settings:
export OMP_NUM_THREADS=4
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

export RX_DURATION=600

#run the application:
mkdir -p slurm_output/$SLURM_JOB_ID

srun -n 1 -c 4 --cpu_bind=cores make receive_file > slurm_output/$SLURM_JOB_ID/rx_1.out &
srun -n 1 -c 4 --cpu_bind=cores make receive_file > slurm_output/$SLURM_JOB_ID/rx_2.out &

sleep 10

srun -n 1 -c 10 --cpu_bind=cores make send_file > slurm_output/$SLURM_JOB_ID/tx_1.out &

sleep 90    # watchdog timeout




