#!/bin/bash

echo "Receiver IP is: $MY_IP"
echo "IP VERSION IS $IP_VERSION"
echo "FT_EXTENSION: $FT_EXTENSION"
echo "FT_PREFIX: $FT_PREFIX"
echo "FT_TIMEOUT: $FT_TIMEOUT"
echo "FT_THREADS: $FT_THREADS"

e2sar_ft -r --ip $MY_IP --path /data --extension $FT_EXTENSION --prefix $FT_PREFIX --timeout $FT_TIMEOUT --withcp --threads $FT_THREADS
