#!/bin/bash

echo "Sender IP is: $MY_IP"
echo "IP VERSION IS $IP_VERSION"
echo "FT_EXTENSION: $FT_EXTENSION"
echo "FT_RATE: $FT_RATE"
echo "SEND_SOCKETS: $SEND_SOCKETS"

e2sar_ft -s --ip $MY_IP --extension $FT_EXTENSION --sockets $SEND_SOCKETS --rate $FT_RATE --smooth --withcp --path /data/
