#!/bin/bash

DEMO_ROOT=`git rev-parse --show-toplevel`
echo $DEMO_ROOT

make -f $DEMO_ROOT/scripts/Makefile.lbadm e2sar_perf E2SAR_PERF_OPTIONS='--send --withcp --rate 0.01 --ini segmenter_config.ini '


