__author__ = 'work'


class Param(object):
    def __init__(self):
        self.param = {}
        self.param["process"] = '1' ##set 1 to pre-process the data
        self.param["reconstruct"] = '1' ##set 1 to perform the reconstruction
        self.param["removeOutliers"] = '1' ##set 1 to remove outlier diffraction patterns
        self.param["lowPassFilter"] = '1' ##set 1 to low pass filter the data
        self.param["file_prefix"] = '' ##prefix used in the the file names before auto-increment
        self.param["dataPath"] = '' ##path to the auto-incremented directory tree
        self.param["dataFile"] = '' ##CXI file to use if not using auto-incremented tree
        self.param["saveFile"] = '0'
        self.param["speFile"] = '' ##SPE file to use if not using auto-incremented tree
        self.param["scanDate"] = '' ##scan date
        self.param["scanNumber"] = '' ##scan number
        self.param["scanID"] = '' ##scan ID
        self.param["scanDir"] = ''
        self.param["fileName"] = ''
        self.param["outputFilename"] = ''
        self.param["bgScanDate"] = ''
        self.param["bgScanNumber"] = ''
        self.param["bgScanID"] = ''
        self.param["interferometer"] = '1' ##set to 1 to use interferometer positions
        self.param["xaxis"] = 'b' ##file code for x axis interferometer data
        self.param["yaxis"] = 'c' ##file code for y axis interferometer data
        self.param["xaxisNo"] = '0' ##file code for x axis interferometer data
        self.param["yaxisNo"] = '0' ##file code for y axis interferometer data
        self.param["pixnm"] = '7' ##requested pixel size in nm
        self.param["sh_sample_y"] = '256' ##final resampled grid size
        self.param["sh_sample_x"] = '256' ##final resampled grid size
        self.param["filter_width"] = '200' ##pixel width of the autocorrelation filter
        self.param['probeThreshold'] = '0.01' ##threshold to use for calculating probe from STXM brightfield
        self.param["ssx"] = '50' ##step size in the x dimension in nm
        self.param["ssy"] = '50' ##step size in the y dimension in nm
        self.param["ssn"] = '10' #number of pixels per scan step
        self.param["xpts"] = '20' ##number of scan points in the x dimension
        self.param["ypts"] = '20' ##number of scan points in the y dimension
        self.param["zd"] = '240' ##zone plate diameter in microns
        self.param["dr"] = '60' ##zone plate outer zone width
        self.param["e"] = '750' ##x-ray energy
        self.param["ccdp"] = '30' ##ccd pixel size in microns
        self.param["ccdz"] = '84.55' ##ccd distance from sample in mm
        self.param["nexp"] = '1' ##number of exposure times per point
        self.param["nl"] = '0.1' ##final lower threshold on the data
        self.param["xcenter"] = '' ##center x pixel in the raw data
        self.param["ycenter"] = '' ##center y pixel in the raw data
        self.param["t_long"] = '0' ##long exposure time
        self.param["t_short"] = '0' ##short exposure time
        self.param["s_threshold"] = '1000' ##upper threshold on saturated pixels
        self.param["nProcesses"] = '48' ##number of pre-processing processes to launch
        self.param["bl"] = 'ns' ##beamline tag                    p = Param()
        self.param["cxi"] = '1' ##set 1 to output to CXI file
        self.param["gpu"] = '1' ##set 1 to use the GPU
        self.param["nIterations"] = '500' ##number of iterations
        self.param["probeMask"] = '1' ##set 1 to use a fourier mask on the probe
        self.param["algorithm"] = 'raar' ##algorithm tag
        self.param["pR"] = '1' ##set 1 to use probe retrieval
        self.param["bR"] = '1' ##set 1 to use background retrieval
        self.param["useStxm"] = '0' ##set 1 to start from the STXM image
        self.param["version"] = '2' ##set 2
        self.param['bg_filename'] = '' ##SPE file with background data if not using auto-increment
        self.param['zpw'] = '100' ##width of the STXM brightfield annulus in pixel units in Fourier space
        self.param['short_filename'] = '0' ##SPE file with short exposures if recorded separately
        self.param['fCCD']='1' ##set 1 if using the fast CCD
        self.param['Year'] = ''
        self.param['Month'] = ''
        self.param['Day'] = ''
        self.param['Scientist'] = ''
        self.param['Sample'] = ''
        self.param['Comment1'] = ''
        self.param['Comment2'] = ''
        self.param['Id'] = ''
        self.param['beamstop'] = '5' ##thickness: 5,10,20
        self.param['useBeamstop'] = '0'
        self.param['processGPU'] = '0' ##set 1 to pre-process on the GPU
        self.param['fv'] = '0' ##set 1 to flip data vertically
        self.param['fh'] = '0' ##set 1 to flip data horizontally
        self.param['transpose'] = '0' ##set 1 to transpose the data
        self.param['sim'] = '0' ##set 1 if this is a simulation
        self.param['usePrevious'] = '0' ##set 1 to start from a previous reconstruction
        self.param['removePhasePlane'] = '1'
        self.param['beta'] = '0.5' #RAAR paramter: 0.5-1.0
        self.param["eta"] = '0.5' ##eta for background retrieval
        self.param['illuminationPeriod'] = '1' #Refine illumination every few iterations
        self.param['backgroundPeriod'] = '1'
        self.param['relaxedFourier'] = '0' #Relaxed Fourier Modulus constraints
        self.param['illuminationIntensities'] = '0' #Enforce illumination Fourier intensities
        self.param['illuminationMask'] = '1' #Enfornce mask on illumination intensities
        self.param['sh_crop'] = '960' #sub-matrix to use of the full fCCD RAW data
        self.param['paramFileName'] = '0'
        self.param['debug'] = '0'
        self.param['fCCD_version'] = '1' #1 for old and 2 for new
        self.param['loopSize'] = '10'
        self.param['nBlocks'] = '4'
        self.param['nGPU'] = '8'
        self.param['nCPU'] = '48'
        self.param['useCluster'] = '0'
        self.param['low_pass'] = '0' #switch to low pass the image because of strong scattering
        self.param['prtf'] = '0'
        self.param['beamStopTransmission'] = '0.015'
        self.param['itnGlobal'] = '0'
        self.param['logFile'] = 'ptychoLog.txt'
        self.param['finalError'] = '0'
        self.param['defocus'] = '0'
        self.param['iModes'] = '1'
        self.param['oModes'] = '1'
        self.param['probeFile'] = ''
        self.param['illuminationIntensitiesFile'] = ''
        self.param['beamstopXshift'] = '-3'
        self.param['beamstopYshift'] = '-5'
        self.param['hostfile'] = '/global/groups/cosmic/host_file'
        self.param['nNodes'] = '4'
        self.param['cpuPerNode'] = '8'
        self.param['gpuPerNode'] = '2'
        self.param['repetition'] = '1'
        self.param['nl_filter'] = '0'
