#!/bin/bash

# Auto-detect MY_IP if not already set
if [ -z "$MY_IP" ]; then
    if [ "$IP_VERSION" = "-4" ]; then
        LB_IP=$(dig +short ejfat-lb.es.net A | tail -1)
    else
        LB_IP=$(dig +short ejfat-lb.es.net AAAA | tail -1)
    fi
    MY_IP=$(ip route get $LB_IP | head -1 | sed 's/^.*src//' | awk '{ print $1 }')
fi

echo "Sender IP is: $MY_IP"
echo "IP VERSION IS $IP_VERSION"
echo "FT_EXTENSION: $FT_EXTENSION"
echo "FT_RATE: $FT_RATE"
echo "SEND_SOCKETS: $SEND_SOCKETS"
echo "DATA_PATH: ${DATA_PATH:-/data}"

e2sar_ft -s --ip $MY_IP --extension $FT_EXTENSION --sockets $SEND_SOCKETS --rate $FT_RATE --smooth --withcp --path ${DATA_PATH:-/data}/
