#!/bin/bash

echo " ---------------------- lbadm help --------------------------------------"
lbadm --help
echo ""
echo ""
echo " ---------------------- e2sar_perf help ---------------------------------"
e2sar_perf --help
